name: run-fusesoc-targets
on: [push]

jobs:
  build-openlane-sky130:
    runs-on: ubuntu-latest
    env:
      REPO : Booth_Multipliers
      VLNV : booth_multipliers
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: Booth_Multipliers
      - run: echo "EDALIZE_LAUNCHER=el_docker" >> $GITHUB_ENV
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=sky130_4xA $VLNV

  lint-verilator:
    runs-on: ubuntu-latest
    env:
      REPO : Booth_Multipliers
      VLNV : booth_multipliers
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: Booth_Multipliers
      - run: sudo apt install verilator
      - run: pip3 install fusesoc
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=lint_4xA $VLNV
